name: mygallerybook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: 4.6.6
  get_storage: ^2.1.1

  http: ^1.2.1
  file_picker: ^8.0.3
  google_fonts: 6.2.1
  fluttertoast: ^8.2.6
  loading_animation_widget: ^1.2.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_otp_text_field: ^1.1.3+2
  system_info:
  path_provider: ^2.1.3
  another_flushbar: ^1.12.30
  share:
  dio:
  http_parser: any
  percent_indicator: ^4.2.3
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  razorpay_flutter: ^1.3.7
  flutter_inappwebview: any
  font_awesome_flutter: ^10.7.0
  webview_flutter: ^4.8.0
  shimmer: ^2.0.0
  pinput: ^5.0.0

  sp_util: ^2.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/App_Icon.png
    - assets/launcherIcon.png
    - assets/launcherIcon.jpg
    - assets/img.png
    - assets/empty.png
    - assets/profile.png
    - assets/soon.png
    - assets/tc.pdf
    - assets/Mygallerybook_splash.jpg
