name: mygallerybook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  google_fonts: 6.2.1
  get: 4.6.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  flutter_otp_text_field: ^1.1.3+2
  file_picker: ^8.0.3
  system_info:
  path_provider: ^2.1.3
  another_flushbar: ^1.12.30
  share:
  dio:
  percent_indicator: ^4.2.3
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  razorpay_flutter: ^1.3.7
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/App_Icon.png
    - assets/launcherIcon.png
    - assets/launcherIcon.jpg
    - assets/img.png
    - assets/empty.png
    - assets/profile.png
    - assets/soon.png
    - assets/tc.pdf
